[package]
name = "builder"
version = "0.1.0"
authors = ["phi <ficarde@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "*"


